title:              PDFZero
email:              help@pdfzero.com
author:             PDFZero
baseurl:            "/blog"
url:                "https://www.pdfzero.com"

# Social Profiles
twitter_username:   PDFZero

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
plugins:
  - jekyll-feed
