title:              PDFZero
email:              help@pdfzero.com
author:             PDFZero
baseurl:            "pdfzero/blog"
url:                "https://www.pdfzero.com"
permalink:          /:title.html
exclude: [
                    "_app",
                    "_config.yml",
                    "Gemfile",
                    "gulpfile.js",
                    "package-lock.json",
                    "package.json"
]

# Social Profiles
twitter_username:   PDFZero

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
plugins:
  - jekyll-feed
